### PR TITLE
[Spark-refactor] Replace List and Map by UnmodifiableXxx

### PR DESCRIPTION
**Pull request by Thespica**
## Proposed changes

Here are the main changes:
- replace List and Map by Unmodifiable from java collection(documentation and test later)
- add some methods for GraphInfo
- move EdgeTriplet into Edge.java file
- upgrade java to 11
- rename package name from `com.alibaba` to `org.apache`
- update license header

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/alibaba/GraphAr/blob/main/CONTRIBUTING.rst) doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

Related issue #409

### CODE REVIEW

**Comment by acezen** [comment]
As discussion in https://github.com/alibaba/GraphAr/discussions/379#discussioncomment-8860670, seems we had a decision that we should use the `UnmodifiableXxx` as the immutable object class. The ImmutableXxx would bring a extra dependency that not comply with the "Keep It Simple, Stupid" principle.

**Comment by acezen** [comment]
JAVA 8 is a very old version that does not support `UnmodifiableXxx` is reasonable. We can drop the support for JAVA 8 and start from JAVA 11.

**Comment by Thespica** [comment]
This PR is ready, take a review please @acezen  @SemyonSinchenko

**Comment by acezen** [comment]
Hi， the rename package name from com.alibaba to org.apache is only apply to main. It' not need to change that in this PR. It would bring a lot of changes that are not related to the feature.

**Review by acezen — APPROVED** [review]
LGTM, thanks  for the work

**Pull request merged**
