### PR TITLE
[Bug][C++] Add implement of property<bool>

### LINKED ISSUE #341: [Bug][C++]: Can not use property<bool>()
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

my code [here](https://github.com/jasinliu/data-migration/blob/main/demo/MaybeBug/show.cpp#L16)

when makes, it throws an error.

image

### Expected Behavior

So, how to use property<bool>()  to get datas of bool type?  Does this @[pr](https://github.com/alibaba/GraphAr/pull/337) work?

### Minimal Reproducible Example

https://github.com/jasinliu/data-migration/blob/main/demo/MaybeBug

### Environment

- Operating system: ubuntu focal
- GraphAr version:latest

### PR DESCRIPTION
**Pull request by jasinliu**
## Proposed changes

As title. 

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/alibaba/GraphAr/blob/main/CONTRIBUTING.rst) doc
- [x] I have signed the CLA
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

close #341 
Also, I think there needs a test contains the check of all types.

### CODE REVIEW

**Comment by acezen** [comment]
hi, @jasinliu, can you help us to create an big issue about this problem and link this PR
to it. That would make the context clear.

**Comment by acezen** [comment]
and about the test cases fulfill, that's good advice. Can you create an issue for that too? Thanks a lot.

**Comment by jasinliu** [comment]
> hi, @jasinliu, can you help us to create an big issue about this problem and link this PR to it. That would make the context clear.

OK, maybe my fault.

**Review by acezen — APPROVED** [review]
LGTM~, hi, @jasinliu, if you create the related issue, please at me to merge this PR.

**Comment by jasinliu** [comment]
> LGTM~, hi, @jasinliu, if you create the related issue, please at me to merge this PR.

Sorry for late😂

**Pull request merged**
