### PR TITLE
[C++][Improvement] Add validation of different levels for builders in C++ library

### PR DESCRIPTION
**Pull request by lixueclaire**
## Proposed changes

Similar to the GraphAr C++ SDK writers, we could add the implementation of various validation levels in the builders (`VerticesBuilder` &` EdgesBuilder`).  A strong validation level could ensure the consistency of data types between the data and meta info before being written.

## Types of changes

What types of changes does your code introduce to GraphAr?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/alibaba/GraphAr/blob/main/CONTRIBUTING.rst) doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

solve issue #171

### CODE REVIEW

**Review by acezen — COMMENTED** [review]
About the `validation level` of writer or builder,  I have some idea, it may not be right, but we can discuss together.

1. As my understanding , beside the global validation level for `builder` and `writer`, you also provide a fine-grained validation that every adding vertex/edge/table could have a validation level itself. The fine-grained validation is a little complicated to me.  In my opinion, the validation for the same builder or writer better to be consistent.
A similar example is the validation level of [MongoDB](https://www.mongodb.com/docs/manual/core/schema-validation/specify-validation-level/)

2. The expose of the `Validate` method which means that the object is not just a `Builder` or `Writer`, but also a `Validator` to user. Do we want to give the context that `Builder` is also a `Validator`?

**Comment by lixueclaire** [comment]
> About the `validation level` of writer or builder, I have some idea, it may not be right, but we can discuss together.
> 
> 1. As my understanding , beside the global validation level for `builder` and `writer`, you also provide a fine-grained validation that every adding vertex/edge/table could have a validation level itself. The fine-grained validation is a little complicated to me.  In my opinion, the validation for the same builder or writer better to be consistent.
>    A similar example is the validation level of [MongoDB](https://www.mongodb.com/docs/manual/core/schema-validation/specify-validation-level/)
> 2. The expose of the `Validate` method which means that the object is not just a `Builder` or `Writer`, but also a `Validator` to user. Do we want to give the context that `Builder` is also a `Validator`?

We expose the method to users so they can check if an operation is valid before applying.

**Comment by acezen** [comment]
> > About the `validation level` of writer or builder, I have some idea, it may not be right, but we can discuss together.
> > 
> > 1. As my understanding , beside the global validation level for `builder` and `writer`, you also provide a fine-grained validation that every adding vertex/edge/table could have a validation level itself. The fine-grained validation is a little complicated to me.  In my opinion, the validation for the same builder or writer better to be consistent.
> >    A similar example is the validation level of [MongoDB](https://www.mongodb.com/docs/manual/core/schema-validation/specify-validation-level/)
> > 2. The expose of the `Validate` method which means that the object is not just a `Builder` or `Writer`, but also a `Validator` to user. Do we want to give the context that `Builder` is also a `Validator`?
> 
> We expose the method to users so they can check if an operation is valid before applying. In my opinion, The `Validator` is a necessary part of `Builder` or `Writer`. It is not used for validate the data itself, but to validate an operation of `Builder` or `Writer`.

understand, that make reason to me (but i still think is a little complicated). We can merge the pull request first and discuss about this at next meeting.

**Review by acezen — APPROVED** [review]
LGTM

**Comment by lixueclaire** [comment]
> > > About the `validation level` of writer or builder, I have some idea, it may not be right, but we can discuss together.
> > > 
> > > 1. As my understanding , beside the global validation level for `builder` and `writer`, you also provide a fine-grained validation that every adding vertex/edge/table could have a validation level itself. The fine-grained validation is a little complicated to me.  In my opinion, the validation for the same builder or writer better to be consistent.
> > >    A similar example is the validation level of [MongoDB](https://www.mongodb.com/docs/manual/core/schema-validation/specify-validation-level/)
> > > 2. The expose of the `Validate` method which means that the object is not just a `Builder` or `Writer`, but also a `Validator` to user. Do we want to give the context that `Builder` is also a `Validator`?
> > 
> > 
> > We expose the method to users so they can check if an operation is valid before applying. In my opinion, The `Validator` is a necessary part of `Builder` or `Writer`. It is not used for validate the data itself, but to validate an operation of `Builder` or `Writer`.
> 
> understand, that make reason to me (but i still think is a little complicated). We can merge the pull request first and discuss about this at next meeting.

I agree with you. This pull request is a step towards aligning the validation levels for Builder with Writer, since Builder is a high-level wrapper of Writer. 
However, we could continue this discussion after merging this change to focus on developing a more comprehensive and consistent approach to validation across all of GraphAr's tools and libraries,  not just for Builder and Writer.

**Pull request merged**
