### PR TITLE
[BugFix][C++] Remove arrow header from GraphAr's header

### LINKED ISSUE #228: [Bug]: `filesystem.h` include the `arrow/dataset/api.h`, graphar headers should not include any arrow headers
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

include `gar/util/filesystem.h` need to install arrow first.

### Expected Behavior

`filesystem.h` should not include any arrow headers.

### Minimal Reproducible Example

write a demo and include `filesystem.h`.

### Environment

- Operating system:
- GraphAr version:

### Link to GraphAr Logs

_No response_

### Further Information

_No response_

### PR DESCRIPTION
**Pull request by acezen**
## Proposed changes

[commit-49685](https://github.com/alibaba/GraphAr/commit/496856839ad170de40b42158cb906474374c7d3d) has include arrow header into graphar' header which we should not do that. Because we can't assume that users's system installed arrow.
## Types of changes

What types of changes does your code introduce to GraphAr?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/alibaba/GraphAr/blob/main/CONTRIBUTING.rst) doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments
Fixed #228

### CODE REVIEW

**Comment by acezen** [comment]
hi, @Ziy1-Tan, this pull request needs your review

**Review by lixueclaire — APPROVED** [review]
LGTM

**Comment by Ziy1-Tan** [comment]
> hi, @Ziy1-Tan, this pull request needs your review

Let me try it.

**Review by Ziy1-Tan — COMMENTED** [review]
shared_ptr<XXX> requires a full definition of the type, so the forward declaration does not work

**Comment by acezen** [comment]
> > hi, @Ziy1-Tan, this pull request needs your review
> 
> I have a little doubt. When arrow is not installed, cmake will automatically build from source code. So we can always guarantee that arrow is installed, right?

the source-build arrow is just use by graphar, it does not install to system, so when user use graphar, we should guarantee they can run with graphar without arrow.

**Comment by acezen** [comment]
> shared_ptr requires a full definition of the type, so the forward declaration does not work

Actually, shared_ptr can work with forward declaration.
https://stackoverflow.com/questions/16588075/forward-declarations-and-shared-ptr

**Comment by acezen** [comment]
This PR still need some refine, like revise the `Expression` as a real wrapper of `arrow::Expression` which not expose the `arrow::Expression` outside.

**Pull request merged**
